[package]
name = "ahdlibya/minecraftclone"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# cmdr
Cmdr = "evaera/cmdr@1.9.0"
# knit 
Knit = "sleitnick/knit@1.4.7"
# janitor
Janitor = "howmanysmall/janitor@1.14.1"
#promise
Promise = "evaera/promise@4.0.0"
# Component
Component = "sleitnick/component@2.4.6"
# Input
Input = "sleitnick/input@2.1.1"
# Option
Option = "sleitnick/option@1.0.4"
# Signal
Signal = "sleitnick/signal@1.2.1"
# Trove 
Trove = "sleitnick/trove@0.5.0"
# Shake
Shake = "sleitnick/shake@0.1.7"